name: copybara

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install GitHub SSH key
        run: |
          mkdir ~/.ssh
          echo $'${{ secrets.SSH_KEY }}' > ~/.ssh/id_rsa
          echo $'${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts

      - name: Install Git config
        run: |
          git config --global user.name "wilmol"
          git config --global user.email willjoemolloy@gmail.com

      - name: Pull Copybara image
        run: docker pull sharelatex/copybara

      - name: Run Copybara
        run: docker run -v ~/.ssh:/root/.ssh -v ~/.gitconfig:/root/.gitconfig -v "$(pwd)":/usr/src/app -i sharelatex/copybara copybara
